### ISSUE TITLE
프로그래머스 1랩 황태현

### ISSUE THREAD

**Issue by clowns123** [ai-creatv/algorithm_FED16#1]
![제목 없음](https://user-images.githubusercontent.com/50760015/88267344-ada7a180-cd0b-11ea-9497-8c636f0570d9.png)
[function.zip](https://github.com/ai-creatv/algorithm_FED16/files/4964746/function.zip)

**Comment by ai-creatv** [comment]
안녕하세요? 과제는 이메일로 제출 부탁드립니다! :)

두 문제 모두 깔끔하게 잘 구현해 주셨습니다.

1번 문제에서 a 변수를 조금 더 의미있는 이름을 쓰면 더 좋을 것 같네요!

수고하셨습니다 :)
