### ISSUE TITLE
알고리즘 1일차 숙제

### ISSUE THREAD

**Issue by SaltPepperSalt** [ai-creatv/algorithm_FED16#2]
[Homework.zip](https://github.com/ai-creatv/algorithm_FED16/files/4993454/Homework.zip)
숙제 제출합니다

**Comment by ai-creatv** [comment]
답변이 늦어 죄송합니다! 깔끔하게 잘 구현해 주셨네요 👍 

1번 문제의 경우 answer 변수가 굳이 없어도 될 것 같다는 점 정도만 피드백 드립니다 :)
