### ISSUE TITLE
Doubly Linked List 구현 과제제출.

### ISSUE THREAD

**Issue by LEE-WOO-SEONG** [ai-creatv/algorithm_FED16#3]
안녕하세요. FED 16기 수강생 이우성입니다.

Doubly Linked List 구현과제 제출드립니다.

아래 repo 참고 부탁드립니다.
감사합니다.

https://github.com/LEE-WOO-SEONG/datastructure-algorithm/blob/master/dataStructures/DoublyLinedList.js

**Comment by ai-creatv** [comment]
안녕하세요? 이우성님, 피드백 드립니다!

우선 대부분 기능을 잘 구현해 주셨습니다 :) 

다만 print 부분이 리스트의 내용을 잘 표현하지 못하는 것 같습니다.

디버그를 위한 상세 정보를 출력하는 것은 따로 구현하고, print는 그대로 내용만 출력하는 것이 좋아 보입니다 :)

과제 레포지토리의 after.js에 정답을 올려두었으니, 참고해 주세요 :)
