### ISSUE TITLE
Doubly Linked List 구현 과제제출.

### ISSUE THREAD

**Issue by Detrox20** [ai-creatv/algorithm_FED16#4]
안녕하세요. FED 16기 수강생 류동우입니다.

Doubly Linked List 구현과제 제출드립니다.

아래 repo 참고 부탁드립니다.
감사합니다.

https://github.com/Detrox20/algorithm-practice/blob/master/doublyLinkedList.js

**Comment by ai-creatv** [comment]
류동우님, 안녕하세요?

충실하게 잘 구현해 주셨습니다! :)

테스트 코드에서도 잘 동작하네요. 수고하셨습니다 :)
